public enum AN_LicenseErrorCode
{
	ERROR_NONE = 0,
	ERROR_RETRY = 1,
	ERROR_CHECK_IN_PROGRESS = 2,
	ERROR_INVALID_PACKAGE_NAME = 3,
	ERROR_INVALID_PUBLIC_KEY = 4,
	ERROR_MISSING_PERMISSION = 5,
	ERROR_NON_MATCHING_UID = 6,
	ERROR_NOT_MARKET_MANAGED = 7,
	ERROR_UNKNOWN = 8
}
